name: Steps in teaching
favicon: null
layout_spectrum: 0.79701
typography_spectrum: 0.68426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8e8d8b'
    - '#ffffff'
    - '#c0bfbb'
    - '#3c3837'
  brandStrength: 0.75
  lightness: 0.5378317323047668
  saturation: 0.9723645604681224
  rhythmicContrast: 0.9211377284955233
purpose: []
